//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iCAREAdmin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public iCAREAdmin()
        {
            this.iCAREWorkers = new HashSet<iCAREWorker>();
        }
    
        public string adminEmail { get; set; }
        public System.DateTime dateHired { get; set; }
        public System.DateTime dateFinished { get; set; }
        public string ID { get; set; }
    
        public virtual iCAREUser iCAREUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<iCAREWorker> iCAREWorkers { get; set; }
    }
}
