//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModificationHistory
    {
        public System.DateTime dateOfModification { get; set; }
        public string description { get; set; }
        public string docID { get; set; }
        public string WorkerID { get; set; }
        public string MHID { get; set; }
    
        public virtual DocumentMetadata DocumentMetadata { get; set; }
        public virtual iCAREWorker iCAREWorker { get; set; }
    }
}
