//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TreatmentRecord
    {
        public string treatmentID { get; set; }
        public string description { get; set; }
        public System.DateTime treatmentDate { get; set; }
        public string WorkerID { get; set; }
        public string PatientID { get; set; }
        public string PatientRecordID { get; set; }
    
        public virtual iCAREWorker iCAREWorker { get; set; }
        public virtual PatientRecord PatientRecord { get; set; }
        public virtual PatientRecord PatientRecord1 { get; set; }
    }
}
